### PR TITLE
Closes #443: Adjust manage dataverse permissions page to our layout

### LINKED ISSUE #443: Adjust manage dataverse permissions page to our layout

### PR DESCRIPTION
**Pull request by sudmar**

### CODE REVIEW

**Review by dbojanek — COMMENTED** [review]
"Assign Role" modal window changes its width after we choose one of the roles we want to assign. Can we have this synchronized?

**Review by dbojanek — COMMENTED** [review]
"Edit Role" modal window - I'm not able to scroll on modal (background page scrolls but not the modal) until I manually resize that modal.

Also: Isn't "Edit Role" modal width narrower that other modals on the Page? Can we set it's width to maybe the same as "Assign Role"?

**Review by dbojanek — CHANGES_REQUESTED** [review]
as commented

**Comment by sudmar** [comment]
> "Edit Role" modal window - I'm not able to scroll on modal (background page scrolls but not the modal) until I manually resize that modal.
> Also: Isn't "Edit Role" modal width narrower that other modals on the Page? Can we set it's width to maybe the same as "Assign Role"?

Just for future reference - these issues were discussed on our team meeting, and we have classified them as minor and postponed fixing them for later, if necessary.

> "Assign Role" modal window changes its width after we choose one of the roles we want to assign. Can we have this synchronized?

You have mentioned being able to fix this via backend - would you do that? There doesn't seem an elegant way to fix this via frontend. I've planned to make this modal start with max width, but doing so via CSS prevents the user from resizing it horizontally at all.

**Comment by sudmar** [comment]
Nevermind, I have figured this out. Please check if everything works as intended.

**Review by dbojanek — APPROVED** [review]

**Pull request merged**
