### PR TITLE
Closes #1045: Make Dataverse app usable at 320px window width

### LINKED ISSUE #1045: Make Dataverse app usable at 320px window width

### PR DESCRIPTION
**Pull request by sudmar**
Closes #1045

### CODE REVIEW

**Comment by dbojanek** [comment]
# 1

image

On file page Dataset citation and file citation do not wrap.

**Comment by dbojanek** [comment]
# 2

On file page, MD5 does not wrap

image

**Comment by dbojanek** [comment]
# 3

On File page, Metadata tab, Downloading url and MD5 are cut off 

image

**Comment by dbojanek** [comment]
# 4

On File page, if filename is long, it doesn't wrap on breadcrumb.

image

**Comment by dbojanek** [comment]
# 5

Text Messages and Banners page doesn't scale well.

image

**Comment by dbojanek** [comment]
# 6

If dataverse has banner, it doesn't scale well.

image

**Comment by dbojanek** [comment]
# 7

If a dataverse has a Logo image with tagline, the tagline doesn't wrap (it's this 'sefgdfgsdfgsd..' text here)

image

**Comment by dbojanek** [comment]
# 8

On edit dataverse metadata, dropdown with selecting metadata is too wide.

image

**Comment by dbojanek** [comment]
# 9

Assign role modal window, Users/Groups too wide

image

**Comment by dbojanek** [comment]
# 10

Add role modal window, weird wrapping and small checkboxes

image

**Comment by dbojanek** [comment]
# 12

On file reorder, file names do not wrap

image

**Comment by dbojanek** [comment]
# 13

On dataset, files tab: search input is extremely narrow:

image

**Comment by dbojanek** [comment]
# 14

Dataset, edit button does not align to page size:

image

**Comment by dbojanek** [comment]
# 15

On dataset -> select guestbook: dataset image is under guestbook name

image

**Comment by dbojanek** [comment]
# 16

Embargo setting modal goes below modal height (this horizontal line thru calendar input), and calendar box doesn't align well

image

**Comment by dbojanek** [comment]
# 17

Dataset Edit -> Permissions -> Dataset: too wide button.
Same for File permissions.

image

**Comment by dbojanek** [comment]
# 18

Dataset Edit -> Permissions -> Assign Role modal : too wide user/groups input
Same for file permissions

image

**Comment by dbojanek** [comment]
# 19

Dataset Edit -> Deaccess dataset: modal has no support for narrower screens.

image

**Comment by dbojanek** [comment]
# 20

File Edit: dropdown allign

image

**Comment by dbojanek** [comment]
# 21

Dashboard -> Manage Users: narrow search input

image

**Comment by sudmar** [comment]
14, 17, 20 - these issues affect only larger font sizes and may be difficult to fix in a way that would work properly on all font/resolution combinations. This is left unfixed for now - after consultations, Krzysiek said that the 320px limit is to be checked mainly on standard font.

The rest of the issues are fixed. Some of these fixes might not apply to standard font size only, as mentioned above.

**Comment by dbojanek** [comment]
Number 5 - still no scale for text messages and banners?

image

**Comment by dbojanek** [comment]
# 22

No banner scaling for "create new banner" page:

image

**Comment by dbojanek** [comment]
# 23

Soma additional scaling for banner is required:

image

**Comment by sudmar** [comment]
22 - fixed, but instead of scaling the image I've made it scrollable, I think it makes it easier for the uploader to review the uploaded content.
23 - fixed

**Review by dbojanek — APPROVED** [review]

**Pull request merged**
