### PR TITLE
Closes #224: Added @elvariable to help ide recognise class types of variables

### LINKED ISSUE #224: Add `@elvariable` comments in xhtml files to help ide recognize class types of variables

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

**Review by MrK191 — CHANGES_REQUESTED** [review]
Those are not all places.

**Review by MrK191 — CHANGES_REQUESTED** [review]
There are still variable missing ex. explicitGroup-new-dialog.xhtml

**Review by MrK191 — CHANGES_REQUESTED** [review]
Merge Conflict

**Comment by dbojanek** [comment]
in file-configure-dropdown-fragment.xhtml elvariable's added in #225

**Comment by MrK191** [comment]
> in file-configure-dropdown-fragment.xhtml elvariable's added in #225

Allright, next time you can use cherry-pick if similar situation occurs.

**Review by MrK191 — APPROVED** [review]

**Pull request merged**
