### PR TITLE
Closes #458: Take care of edit metadata UI

### LINKED ISSUE #458: Take care of edit metadata UI.

### PR DESCRIPTION
**Pull request by sudmar**
Also includes fix for the missing "tick" icon in some checkboxes

### CODE REVIEW

**Comment by MrK191** [comment]
Shouldn't the Save changes and Cancel button be like on other pages?

**Comment by sudmar** [comment]
Somehow I didn't commit all the changes, should be fixed now

**Comment by MrK191** [comment]
The "Cancel" button still has invisible background for me.

**Comment by sudmar** [comment]
@MrK191 on which page are you checking this exactly?

**Review by MrK191 — APPROVED** [review]

**Pull request merged**
