### PR TITLE
Closes #1026: Make manage groups page wcag complaint

### LINKED ISSUE #1026: Make manage groups page wcag complaint

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

**Review by dbojanek — COMMENTED** [review]
image

Edit Group dialog is now broken.

**Comment by dbojanek** [comment]
image

Possibly not in this task, but we have to fix asterisk (*) and question mark (?) display. Now by default on my resolution they both display in new line for 'Group Identfier'

**Review by dbojanek — CHANGES_REQUESTED** [review]
As commented

**Comment by madryk** [comment]
> Possibly not in this task, but we have to fix asterisk (*) and question mark (?) display. Now by default on my resolution they both display in new line for 'Group Identfier'

Probably your theme wasn't updated - I was correcting it

**Review by dbojanek — APPROVED** [review]

**Pull request merged**
