### PR TITLE
Closes #940: Implement changing font size mechanism

### LINKED ISSUE #940: Implement changing font size mechanism

### PR DESCRIPTION
**Pull request by sudmar**
Closes #940

### CODE REVIEW

**Review by dbojanek — COMMENTED** [review]
# 1

image

This middle button is weird with 'a' being cut in half.

**Comment by dbojanek** [comment]
# 2

image

These don't scale well

**Comment by dbojanek** [comment]
# 3

image

'Username/Email'

**Comment by dbojanek** [comment]
# 4

image

On 'My data'

**Comment by dbojanek** [comment]
# 5

image

TextEditor doesn't change its size (potential issue)

**Comment by dbojanek** [comment]
# 6

image

Edit dataverse metadata: 
Dotted list don't allign well with the rest

**Comment by dbojanek** [comment]
# 7

image

Manage permissions:
Button gets cut.

Same happens in dataset permissions.

**Comment by dbojanek** [comment]
# 8

image

Manage Groups:
Value in "group id" is being cut

**Comment by dbojanek** [comment]
# 9

image

Manage guestbooks: buttons don't align well

**Comment by dbojanek** [comment]
# 10

image

Edit tags: too narrow modal or to wide input

**Comment by dbojanek** [comment]
# 11

image

On embargo edit: not able to scroll page down to show whole date picker.
Maybe we can live with that, user with mouse can drag modal up, user who uses only keyboard pics dates from list and not from datePicker anyway.

**Review by dbojanek — CHANGES_REQUESTED** [review]
We still gotta find why columns don't display properly on my local instance.

**Comment by sudmar** [comment]
[#1](https://github.com/CeON/dataverse/pull/1035#pullrequestreview-418036462) - this was an intentional design choice, but after talking to madryk I've changed it to a single uppercase letter A. It looks better now.
[#2](https://github.com/CeON/dataverse/pull/1035#issuecomment-633859098) - I've changed it so that the dataverse/dataset/file icons are always near checkboxes and the text overflows to the new line, I think it's the best I could do given the limited space available.
[#5](https://github.com/CeON/dataverse/pull/1035#issuecomment-633867673) - fixed
[#6](https://github.com/CeON/dataverse/pull/1035#issuecomment-633868153) - fixed
[#7](https://github.com/CeON/dataverse/pull/1035#issuecomment-633870386) & [#8](https://github.com/CeON/dataverse/pull/1035#issuecomment-633872216) will be handled in a separate task: #1071 
[#9](https://github.com/CeON/dataverse/pull/1035#issuecomment-633881903) - fixed
[#11](https://github.com/CeON/dataverse/pull/1035#issuecomment-633886177) - fixed

These issues were related to broken columns and should be fixed now:
[#3](https://github.com/CeON/dataverse/pull/1035#issuecomment-633860223) 
[#4](https://github.com/CeON/dataverse/pull/1035#issuecomment-633861780) 
[#10](https://github.com/CeON/dataverse/pull/1035#issuecomment-633882785)

**Comment by dbojanek** [comment]
# 12

image

Shouldn't the checkbox be enlarged?

**Comment by dbojanek** [comment]
# 13
On file page - huge file miniatures

**Comment by dbojanek** [comment]
# 14

image

On add new license modal, upload file button is partially hidden.

**Comment by dbojanek** [comment]
# 15

image


probably not for this task but I'll add it as a reminder - values are hidden.

**Comment by dbojanek** [comment]
# 16

image

I think we should keep "Advanced search" link in one line without line break.

**Comment by sudmar** [comment]
[#12](https://github.com/CeON/dataverse/pull/1035#issuecomment-637372727) - fixed
[#13](https://github.com/CeON/dataverse/pull/1035#issuecomment-637374058) - reverted the changes
[#14](https://github.com/CeON/dataverse/pull/1035#issuecomment-633867673) - fixed, this modal (and some others) had columns made in a different way and the mobile mode didn't engage as it should
[#15](https://github.com/CeON/dataverse/pull/1035#issuecomment-637378975) will be handled in a separate task: #1071 
[#16](https://github.com/CeON/dataverse/pull/1035#issuecomment-637380577) - fixed, also fixed the incorrect height of Metrics button

**Comment by dbojanek** [comment]
# 17

image

On this component where we move items from one side to the other buttons didn't scale (example: on create new dataverse).
The same goes for 'cancel upload' button on uploading a file (gotta have file big enough to upload longer than a fraction of a second to see it)

**Comment by sudmar** [comment]
Fixed

**Review by dbojanek — APPROVED** [review]

**Pull request merged**
