### PR TITLE
Closes #413: Fixed facets translations on my_data page

### LINKED ISSUE #413: Fix 'Publication Status' facets translations on 'My Data' page

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

**Comment by madryk** [comment]
As we are working on translation of facets on this page. Could we also translate. Top buttons where we remove filters?
And also "Role" - is not polish

**Review by madryk — COMMENTED** [review]
As we are working on translation of facets on this page. Could we also translate. Top buttons where we remove filters?
And also "Role" - is not polish
Or you prefer to do it in separate tsk?

**Comment by dbojanek** [comment]
"Role" are actually polish (plural from "Rola")

**Comment by madryk** [comment]
Hmm... It's weird because other facets have singular form

**Comment by dbojanek** [comment]
I'll change it to singular form then. It's better anyway.

**Review by madryk — APPROVED** [review]

**Pull request merged**
