### PR TITLE
Closes #698: Switched to OpenJDK in travis.yml to make the Travis build run

### LINKED ISSUE #698: Current Travis CI configuration does not work with Java 8
Travis build crashes with error:

```
install-jdk.sh 2020-01-14
Expected feature release number in range of 9 to 15, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

Failing build: https://travis-ci.com/chopeen/dataverse/builds/150629595

More information: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/4

### PR DESCRIPTION
**Pull request by chopeen**
## Travis builds

https://travis-ci.com/chopeen/dataverse

## Pull Request Checklist

- [x] Unit [tests][] completed
- [x] Integration [tests][]: None
- [x] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [x] [Documentation][docs] completed
- [x] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

**Comment by chopeen** [comment]
This PR fixes #698.

**Comment by MrK191** [comment]
I was searching wiki and I found out that you should be able to download java 8 on newest ubuntu - https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support if you use openjdk8.

**Review by MrK191 — CHANGES_REQUESTED** [review]
I was searching wiki and I found out that you should be able to download java 8 on newest ubuntu - https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support if you use openjdk8.

**Comment by chopeen** [comment]
As suggested, I reverted my previous change and switched from `oraclejdk8` to `openjdk8` instead.

The build was successful - https://github.com/chopeen/dataverse/runs/469815387.

**Review by MrK191 — CHANGES_REQUESTED** [review]
Imo you could also change the ubuntu to "bionic" since from the logs i can see that Travis uses v16 which is older. I'm not sure how Travis decides which os version to use, but it would be safer if we would control os version.

**Comment by chopeen** [comment]
Travis has no logic for that, I think - it simply uses Xenial by default (https://docs.travis-ci.com/user/reference/overview/#linux).

Build with Bionic: :heavy_check_mark: https://github.com/chopeen/dataverse/runs/469874009

**Review by MrK191 — APPROVED** [review]

**Pull request merged**
